const DUMMY_RESPONSES = [
  'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin lobortis semper purus sit amet dictum. Duis leo velit, iaculis quis odio et, molestie egestas ipsum. Aliquam accumsan est ut sapien cursus fringilla. In egestas ligula in quam fermentum, eget mattis diam congue. Morbi vel lorem quis purus tristique pharetra vitae sed turpis. Duis iaculis orci interdum malesuada vestibulum. Suspendisse tristique ipsum turpis, sed porttitor velit maximus in.',
  'Ut sit amet felis ac nisl fringilla sollicitudin sed a libero. Nulla imperdiet velit mi, eget posuere justo facilisis vel. Nullam vestibulum augue quis purus mattis, ultricies suscipit quam eleifend. Duis odio nisl, venenatis eget neque vitae, efficitur bibendum nisl. Aliquam sed massa vitae lacus semper facilisis sed eget eros. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Integer quis turpis eget ipsum posuere viverra. Fusce interdum placerat diam, sit amet aliquet erat. Cras dui ante, sollicitudin in lacus id, interdum dignissim erat. Cras at dapibus lectus.',
  'Donec sagittis fringilla imperdiet. Nulla luctus accumsan orci in auctor. Morbi euismod mi a interdum vulputate. Vivamus consequat nibh justo, sed egestas eros dictum non. Aliquam placerat a tellus at aliquam. Fusce feugiat vitae turpis sed commodo. Suspendisse hendrerit velit ex, rhoncus elementum tortor pharetra at. Sed fringilla felis in nisl dapibus tempus. Suspendisse euismod in nunc nec porta. Curabitur ac pharetra diam, ac tincidunt dui. Vestibulum sagittis feugiat lacus eget blandit. Proin et aliquet enim. Sed id mauris ex. Aliquam ac velit nisi. Maecenas sed semper nisl',
  'Morbi efficitur ante tortor, at cursus mi ultrices ut. Aliquam massa metus, facilisis eu mi id, convallis molestie nisl. Duis accumsan diam non ultrices volutpat. Aenean sodales ipsum vitae massa maximus scelerisque. Sed condimentum justo pulvinar magna viverra, at facilisis turpis euismod. Integer quis ligula justo. Mauris pellentesque mollis lorem. Aenean vel consectetur sem. Donec vitae consequat lectus. Etiam vehicula convallis cursus. Curabitur in felis et diam malesuada consectetur eget vel elit. Maecenas eleifend fringilla nunc, at tincidunt quam laoreet euismod. Proin et condimentum massa, sit amet accumsan lacus. Nullam sodales felis ac neque fringilla, quis bibendum sem auctor.',
  'Morbi luctus dictum tortor, vel suscipit diam viverra vitae. Etiam tempus tellus et ipsum sodales auctor. Nam ac finibus augue. Curabitur nec massa metus. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis egestas. Phasellus finibus risus ut mattis egestas. In consequat sagittis mi, quis consequat erat tincidunt vitae. Ut nunc massa, ultricies at porta ut, cursus a turpis. Aliquam ornare nulla vitae tortor porta fermentum.',
];

export default DUMMY_RESPONSES;
